const db=require('../config/database');
function cents(rows){for(const row of rows)for(const key of Object.keys(row))if(key.endsWith('Cents'))row[key]=Number(row[key]||0);return rows}
function filters(f={},alias=''){const p=alias?`${alias}.`:'';const clauses=[],params=[];if(f.start){params.push(f.start);clauses.push(`DATE(${p}created_at)>= $${params.length}`)}if(f.end){params.push(f.end);clauses.push(`DATE(${p}created_at)<= $${params.length}`)}return{sql:clauses.length?` AND ${clauses.join(' AND ')}`:'',params}}
class AdminFinance{
 static async summary(){const rows=(await db.query(`SELECT(SELECT COUNT(*) FROM users)AS "totalUsers",(SELECT COUNT(*) FROM subscriptions WHERE status='active')AS "activeSubscriptions",(SELECT COALESCE(SUM(amount_cents),0)FROM payments WHERE status IN('approved','paid')AND YEAR(COALESCE(paid_at,created_at))=YEAR(UTC_DATE())AND MONTH(COALESCE(paid_at,created_at))=MONTH(UTC_DATE()))AS "monthlyRevenueCents",((SELECT COALESCE(SUM(amount_cents),0)FROM system_expenses WHERE YEAR(occurred_on)=YEAR(UTC_DATE())AND MONTH(occurred_on)=MONTH(UTC_DATE()))+(SELECT COALESCE(SUM(amount_cents),0)FROM cost_entries WHERE YEAR(occurred_on)=YEAR(UTC_DATE())AND MONTH(occurred_on)=MONTH(UTC_DATE())))AS "monthlyExpensesCents"`)).rows;const s=cents(rows)[0];s.monthlyResultCents=s.monthlyRevenueCents-s.monthlyExpensesCents;return s}
 static async users(){return(await db.query(`SELECT u.id,u.name,u.email,u.role,u.plan_name AS "planName",u.credits_remaining AS "creditsRemaining",u.created_at AS "createdAt",(SELECT s.status FROM subscriptions s WHERE s.user_id=u.id ORDER BY s.created_at DESC LIMIT 1)AS "subscriptionStatus" FROM users u ORDER BY u.created_at DESC LIMIT 500`)).rows}
 static async payments(){return cents((await db.query(`SELECT p.id,u.name,u.email,p.amount_cents AS "amountCents",p.fee_cents AS "feeCents",p.net_amount_cents AS "netAmountCents",p.currency,p.status,p.description,p.payment_method AS "paymentMethod",p.payment_type AS "paymentType",p.provider_payment_id AS "providerPaymentId",p.paid_at AS "paidAt",p.created_at AS "createdAt" FROM payments p JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC LIMIT 500`)).rows)}
 static async expenses(){return cents((await db.query(`SELECT id,category,description,amount_cents AS "amountCents",occurred_on AS "occurredOn",recurring,created_at AS "createdAt" FROM system_expenses ORDER BY occurred_on DESC LIMIT 200`)).rows)}
 static async createExpense(userId,d){const id=db.uuid();await db.query(`INSERT INTO system_expenses(id,category,description,amount_cents,occurred_on,recurring,created_by)VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,d.category,d.description,d.amountCents,d.occurredOn,d.recurring,userId]);return{id}}
 static async removeExpense(id){return(await db.query('DELETE FROM system_expenses WHERE id=$1',[id])).rowCount>0}
 static async operations(){return(await db.query(`SELECT(SELECT COUNT(*)FROM users)AS "totalUsers",(SELECT COUNT(*)FROM users WHERE email_verified_at IS NOT NULL)AS "verifiedUsers",(SELECT COUNT(*)FROM projects)AS "totalProjects",(SELECT COUNT(*)FROM videos)AS "totalVideos",(SELECT COUNT(*)FROM videos WHERE status='ready')AS "readyVideos",(SELECT COUNT(*)FROM videos WHERE status='failed')AS "failedVideos",(SELECT COUNT(*)FROM schedules WHERE status='scheduled')AS "scheduledPosts",(SELECT COUNT(*)FROM social_accounts)AS "socialAccounts"`)).rows[0]}
 static async updateUser(id,d){await db.query('UPDATE users SET credits_remaining=$2,plan_name=$3 WHERE id=$1',[id,d.creditsRemaining,d.planName]);return(await db.query(`SELECT id,name,email,plan_name AS "planName",credits_remaining AS "creditsRemaining",role FROM users WHERE id=$1`,[id])).rows[0]||null}
 static async clients(){return cents((await db.query(`SELECT u.id,u.name,u.email,u.plan_name AS "planName",u.credits_remaining AS "creditsRemaining",u.email_verified_at AS "emailVerifiedAt",u.created_at AS "createdAt",(SELECT s.status FROM subscriptions s WHERE s.user_id=u.id ORDER BY s.created_at DESC LIMIT 1)AS "subscriptionStatus",COALESCE((SELECT SUM(p.amount_cents)FROM payments p WHERE p.user_id=u.id AND p.status IN('approved','paid')),0)AS "totalPaidCents",(SELECT COUNT(*)FROM payments p WHERE p.user_id=u.id AND p.status IN('approved','paid'))AS "paymentCount" FROM users u ORDER BY u.created_at DESC LIMIT 500`)).rows)}
 static async analytics(f={}){const conditions=[],params=[];if(f.start){params.push(f.start);conditions.push(`DATE(COALESCE(p.paid_at,p.created_at)) >= $${params.length}`)}if(f.end){params.push(f.end);conditions.push(`DATE(COALESCE(p.paid_at,p.created_at)) <= $${params.length}`)}if(f.clientId){params.push(f.clientId);conditions.push(`p.user_id=$${params.length}`)}if(f.plan){params.push(f.plan);conditions.push(`u.plan_name=$${params.length}`)}if(f.paymentType){params.push(f.paymentType);conditions.push(`COALESCE(p.payment_type,p.payment_method)=$${params.length}`)}const where=conditions.length?`WHERE ${conditions.join(' AND ')}`:'';const payments=cents((await db.query(`SELECT p.id,u.id AS "userId",u.name,u.email,u.plan_name AS "planName",p.amount_cents AS "amountCents",p.fee_cents AS "feeCents",p.net_amount_cents AS "netAmountCents",p.status,p.payment_type AS "paymentType",p.payment_method AS "paymentMethod",p.paid_at AS "paidAt",p.created_at AS "createdAt" FROM payments p JOIN users u ON u.id=p.user_id ${where} ORDER BY p.created_at DESC`,params)).rows);const costConditions=[],costParams=[];if(f.start){costParams.push(f.start);costConditions.push(`c.occurred_on >= $${costParams.length}`)}if(f.end){costParams.push(f.end);costConditions.push(`c.occurred_on <= $${costParams.length}`)}if(f.clientId){costParams.push(f.clientId);costConditions.push(`c.user_id=$${costParams.length}`)}if(f.plan){costParams.push(f.plan);costConditions.push(`u.plan_name=$${costParams.length}`)}const costWhere=costConditions.length?`WHERE ${costConditions.join(' AND ')}`:'';const costs=cents((await db.query(`SELECT c.id,c.category,c.description,c.amount_cents AS "amountCents",c.occurred_on AS "occurredOn",u.id AS "userId",u.name,v.id AS "videoId",v.title AS "videoTitle" FROM cost_entries c LEFT JOIN users u ON u.id=c.user_id LEFT JOIN videos v ON v.id=c.video_id ${costWhere} ORDER BY c.occurred_on DESC`,costParams)).rows);const delinquency=(await db.query(`SELECT s.id,u.id AS "userId",u.name,u.email,u.plan_name AS "planName",s.status,s.current_period_end AS "dueAt",s.updated_at AS "updatedAt" FROM subscriptions s JOIN users u ON u.id=s.user_id WHERE(s.status IN('pending','paused')OR(s.status='active'AND s.current_period_end<NOW())) ORDER BY s.updated_at DESC`)).rows;const approved=payments.filter(p=>['approved','paid'].includes(p.status)),refunds=payments.filter(p=>['refunded','charged_back'].includes(p.status));return{summary:{grossRevenueCents:approved.reduce((s,p)=>s+p.amountCents,0),netRevenueCents:approved.reduce((s,p)=>s+p.netAmountCents,0),directCostsCents:costs.reduce((s,c)=>s+c.amountCents,0),refundsCents:refunds.reduce((s,p)=>s+p.amountCents,0),delinquentCount:delinquency.length},payments,costs,delinquency,refunds,clientProfit:[],videoProfit:[]}}
 static async report(){const a=await this.analytics({});return{summary:{...a.summary,feesCents:a.summary.grossRevenueCents-a.summary.netRevenueCents,expensesCents:a.summary.directCostsCents,resultCents:a.summary.netRevenueCents-a.summary.directCostsCents},months:[]}}
 static async createCost(createdBy,d){const id=db.uuid();await db.query(`INSERT INTO cost_entries(id,user_id,video_id,category,description,amount_cents,occurred_on,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,d.userId||null,d.videoId||null,d.category,d.description,d.amountCents,d.occurredOn,createdBy]);return{id}}
 static async costTargets(){return{users:(await db.query(`SELECT id,name,email,plan_name AS "planName" FROM users ORDER BY name`)).rows,videos:(await db.query(`SELECT v.id,v.title,p.user_id AS "userId" FROM videos v JOIN projects p ON p.id=v.project_id WHERE v.status='ready' ORDER BY v.title`)).rows}}
 static async validTarget(userId,videoId){if(!videoId)return true;return Boolean((await db.query(`SELECT v.id FROM videos v JOIN projects p ON p.id=v.project_id WHERE v.id=$1 AND p.user_id=$2`,[videoId,userId])).rows[0])}
 static async removeCost(id){return(await db.query('DELETE FROM cost_entries WHERE id=$1',[id])).rowCount>0}
}
module.exports=AdminFinance;
