const db=require('../config/database');
class Billing{
 static async plans(activeOnly=true){return(await db.query(`SELECT id,name,price_cents AS "priceCents",credits,mercado_pago_plan_id AS "mercadoPagoPlanId",active FROM subscription_plans ${activeOnly?'WHERE active=TRUE':''} ORDER BY price_cents`)).rows}
 static async plan(id){return(await db.query('SELECT id,name,price_cents AS "priceCents",credits FROM subscription_plans WHERE id=$1 AND active=TRUE',[id])).rows[0]||null}
 static async mySubscription(userId){return(await db.query(`SELECT s.id,s.plan,s.status,s.plan_id AS "planId",s.provider,s.current_period_end AS "currentPeriodEnd",s.provider_subscription_id AS "providerSubscriptionId",p.name AS "planName",p.price_cents AS "priceCents",p.credits FROM subscriptions s LEFT JOIN subscription_plans p ON p.id=s.plan_id WHERE s.user_id=$1 ORDER BY s.created_at DESC LIMIT 1`,[userId])).rows[0]||null}
 static async myPayments(userId){return(await db.query(`SELECT id,provider,provider_payment_id AS "providerPaymentId",amount_cents AS "amountCents",currency,status,description,payment_method AS "paymentMethod",payment_type AS "paymentType",paid_at AS "paidAt",created_at AS "createdAt" FROM payments WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50`,[userId])).rows}
 static async payment(userId,id){return(await db.query(`SELECT id,provider,provider_payment_id AS "providerPaymentId",amount_cents AS "amountCents",currency,status,description,payment_method AS "paymentMethod",payment_type AS "paymentType",paid_at AS "paidAt",created_at AS "createdAt" FROM payments WHERE user_id=$1 AND id=$2`,[userId,id])).rows[0]||null}
 static async adminPayment(id){return(await db.query(`SELECT id,provider,provider_payment_id AS "providerPaymentId",amount_cents AS "amountCents",status FROM payments WHERE id=$1`,[id])).rows[0]||null}
 static async markRefunded(id){await db.query("UPDATE payments SET status='refunded',net_amount_cents=0 WHERE id=$1",[id]);return this.adminPayment(id)}
 static async createPending(userId,plan,externalReference){const id=db.uuid();await db.query(`INSERT INTO subscriptions(id,user_id,provider,plan,status,plan_id,external_reference) VALUES($1,$2,'mercado_pago',$3,'pending',$4,$5)`,[id,userId,plan.name,plan.id,externalReference]);return{id}}
 static async activateFree(userId,plan){return db.withTransaction(async client=>{const existing=await client.query("SELECT id FROM subscriptions WHERE user_id=$1 AND provider='internal' AND plan_id=$2 AND status='active'",[userId,plan.id]);if(!existing.rows[0]){await client.query(`INSERT INTO subscriptions(id,user_id,provider,plan,status,plan_id,external_reference) VALUES($1,$2,'internal',$3,'active',$4,$5)`,[db.uuid(),userId,plan.name,plan.id,`free-${userId}-${Date.now()}`]);await client.query("INSERT INTO credit_transactions(id,user_id,amount,type,description)VALUES($1,$2,$3,'grant',$4)",[db.uuid(),userId,plan.credits,`Créditos do plano ${plan.name}`])}await client.query('UPDATE users SET plan_name=$2,credits_remaining=GREATEST(credits_remaining,$3),credits_valid_until=NULL WHERE id=$1',[userId,plan.name,plan.credits]);return{activated:true}})}
 static async attachProvider(id,providerId){await db.query('UPDATE subscriptions SET provider_subscription_id=$2 WHERE id=$1',[id,providerId])}
 static async removePending(id){await db.query("DELETE FROM subscriptions WHERE id=$1 AND status='pending'",[id])}
 static async cancel(userId,id){const current=await db.query(`SELECT id,provider,provider_subscription_id AS "providerSubscriptionId" FROM subscriptions WHERE id=$1 AND user_id=$2 AND status IN('active','pending','paused')`,[id,userId]);if(!current.rows[0])return null;await db.query("UPDATE subscriptions SET status='cancelled' WHERE id=$1",[id]);return current.rows[0]}
 static async syncSubscription(providerId,data){const statusMap={authorized:'active',paused:'paused',cancelled:'cancelled',pending:'pending'},status=statusMap[data.status]||data.status||'pending',validUntil=data.next_payment_date||null;return db.withTransaction(async client=>{const found=await client.query('SELECT user_id,plan_id FROM subscriptions WHERE provider_subscription_id=$1',[providerId]);const subscription=found.rows[0];if(!subscription)return null;await client.query('UPDATE subscriptions SET status=$2,current_period_end=$3 WHERE provider_subscription_id=$1',[providerId,status,validUntil]);if(status!=='active')return subscription;const plan=(await client.query('SELECT id,name,credits FROM subscription_plans WHERE id=$1 AND active=TRUE',[subscription.plan_id])).rows[0];if(!plan)return subscription;const cycle=validUntil||data.date_created||'initial',referenceKey=`mercado-pago:${providerId}:${cycle}`,grantId=db.uuid();const grant=await client.query("INSERT IGNORE INTO credit_transactions(id,user_id,amount,type,description,expires_at,reference_key)VALUES($1,$2,$3,'grant',$4,$5,$6)",[grantId,subscription.user_id,plan.credits,`Créditos do plano ${plan.name}`,validUntil,referenceKey]);if(grant.rowCount)await client.query('UPDATE users SET plan_name=$2,credits_remaining=GREATEST(credits_remaining,$3),credits_valid_until=$4 WHERE id=$1',[subscription.user_id,plan.name,plan.credits,validUntil]);return{...subscription,creditsGranted:Boolean(grant.rowCount)}})}
 static async upsertPayment(data){const sub=(await db.query('SELECT id,user_id FROM subscriptions WHERE external_reference=$1 ORDER BY created_at DESC LIMIT 1',[data.externalReference])).rows[0];if(!sub)return null;const id=db.uuid();await db.query(`INSERT INTO payments(id,user_id,subscription_id,provider,provider_payment_id,amount_cents,currency,status,description,paid_at,payment_method,payment_type,fee_cents,net_amount_cents)VALUES($1,$2,$3,'mercado_pago',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON DUPLICATE KEY UPDATE amount_cents=VALUES(amount_cents),currency=VALUES(currency),status=VALUES(status),description=VALUES(description),paid_at=VALUES(paid_at),payment_method=VALUES(payment_method),payment_type=VALUES(payment_type),fee_cents=VALUES(fee_cents),net_amount_cents=VALUES(net_amount_cents)`,[id,sub.user_id,sub.id,data.providerPaymentId,data.amountCents,data.currency,data.status,data.description,data.paidAt,data.paymentMethod,data.paymentType,data.feeCents,data.netAmountCents]);const payment=(await db.query("SELECT id,user_id AS \"userId\" FROM payments WHERE provider='mercado_pago' AND provider_payment_id=$1",[data.providerPaymentId])).rows[0];return payment||null}
}
module.exports=Billing;
