const db=require('../config/database');
const fields=`s.id,s.user_id AS "userId",s.title,s.platform,s.caption,s.scheduled_at AS "scheduledAt",s.status,s.video_id AS "videoId",s.social_account_id AS "socialAccountId",s.publication_error AS "publicationError",s.provider_publication_id AS "providerPublicationId",s.published_at AS "publishedAt",s.created_at AS "createdAt",s.updated_at AS "updatedAt",a.account_name AS "accountName",a.status AS "accountStatus",a.token_expires_at AS "tokenExpiresAt",a.encrypted_credentials AS "encryptedCredentials",a.provider_account_id AS "providerAccountId",v.title AS "videoTitle",v.file_url AS "videoFileUrl"`;
class Schedule{
 static async list(userId){const{rows}=await db.query(`SELECT ${fields.replace(',a.encrypted_credentials AS "encryptedCredentials"','')} FROM schedules s LEFT JOIN social_accounts a ON a.id=s.social_account_id LEFT JOIN videos v ON v.id=s.video_id WHERE s.user_id=$1 ORDER BY s.scheduled_at DESC`,[userId]);return rows}
 static async create(userId,d){const id=db.uuid();await db.query(`INSERT INTO schedules(id,user_id,title,platform,caption,scheduled_at,social_account_id,video_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,userId,d.title,d.platform,d.caption,d.scheduledAt,d.socialAccountId,d.videoId]);return(await db.query(`SELECT id,title,platform,caption,scheduled_at AS "scheduledAt",status,social_account_id AS "socialAccountId",video_id AS "videoId",created_at AS "createdAt" FROM schedules WHERE id=$1`,[id])).rows[0]}
 static async due(){return db.withTransaction(async client=>{const pending=await client.query(`SELECT id FROM schedules WHERE status='scheduled' AND scheduled_at<=NOW() ORDER BY scheduled_at LIMIT 5 FOR UPDATE SKIP LOCKED`);if(!pending.rows.length)return[];const ids=pending.rows.map(row=>row.id),marks=ids.map(()=>'?').join(',');await client.query(`UPDATE schedules SET status='publishing' WHERE id IN(${marks})`,ids);const result=await client.query(`SELECT ${fields} FROM schedules s JOIN social_accounts a ON a.id=s.social_account_id JOIN videos v ON v.id=s.video_id WHERE s.id IN(${marks})`,ids);return result.rows})}
 static async published(id,providerId){await db.query(`UPDATE schedules SET status='published',provider_publication_id=$2,published_at=NOW(),publication_error=NULL,updated_at=NOW() WHERE id=$1`,[id,providerId||null])}
 static async failed(id,error){await db.query(`UPDATE schedules SET status='failed',publication_error=$2,updated_at=NOW() WHERE id=$1`,[id,String(error).slice(0,500)])}
 static async remove(userId,id){const{rowCount}=await db.query(`UPDATE schedules SET status='cancelled',updated_at=NOW() WHERE id=$1 AND user_id=$2 AND status='scheduled'`,[id,userId]);return rowCount>0}
}
module.exports=Schedule;
