const db=require('../config/database');
const fields=`id,platform,account_name AS "accountName",profile_url AS "profileUrl",CASE WHEN token_expires_at<=NOW() THEN 'expired' ELSE status END AS status,provider_account_id AS "providerAccountId",token_expires_at AS "tokenExpiresAt",scopes,last_checked_at AS "lastCheckedAt",created_at AS "createdAt",updated_at AS "updatedAt"`;
class SocialAccount{
 static async list(userId){const{rows}=await db.query(`SELECT ${fields} FROM social_accounts WHERE user_id=$1 ORDER BY platform,account_name`,[userId]);return rows}
 static async find(userId,id){const{rows}=await db.query(`SELECT ${fields},encrypted_credentials AS "encryptedCredentials" FROM social_accounts WHERE user_id=$1 AND id=$2`,[userId,id]);return rows[0]||null}
 static async create(userId,data){const id=db.uuid();await db.query(`INSERT INTO social_accounts(id,user_id,platform,account_name,profile_url,encrypted_credentials)VALUES($1,$2,$3,$4,$5,$6)`,[id,userId,data.platform,data.accountName,data.profileUrl||null,data.encryptedCredentials||null]);return(await db.query(`SELECT ${fields} FROM social_accounts WHERE id=$1`,[id])).rows[0]}
 static async connect(userId,data){await db.query(`INSERT INTO social_accounts(id,user_id,platform,account_name,profile_url,status,provider_account_id,encrypted_credentials,token_expires_at,scopes,last_checked_at)VALUES($1,$2,$3,$4,$5,'connected',$6,$7,$8,$9,NOW()) ON DUPLICATE KEY UPDATE profile_url=VALUES(profile_url),status='connected',provider_account_id=VALUES(provider_account_id),encrypted_credentials=VALUES(encrypted_credentials),token_expires_at=VALUES(token_expires_at),scopes=VALUES(scopes),last_checked_at=NOW()`,[db.uuid(),userId,data.platform,data.accountName,data.profileUrl||null,data.providerAccountId,data.encryptedCredentials,data.tokenExpiresAt,data.scopes]);const{rows}=await db.query(`SELECT ${fields} FROM social_accounts WHERE user_id=$1 AND platform=$2 AND account_name=$3`,[userId,data.platform,data.accountName]);return rows[0]}
 static async remove(userId,id){const{rowCount}=await db.query('DELETE FROM social_accounts WHERE user_id=$1 AND id=$2',[userId,id]);return rowCount>0}
}
module.exports=SocialAccount;
