const jwt=require('jsonwebtoken'),vault=require('./credentialVault');
const base=()=>`${(process.env.OAUTH_REDIRECT_BASE||`${process.env.PUBLIC_API_URL||'http://localhost:3000'}/api/social-accounts/oauth`).replace(/\/$/,'')}`;
const providers={
 Instagram:{clientId:'INSTAGRAM_CLIENT_ID',secret:'INSTAGRAM_CLIENT_SECRET',authorize:'https://www.instagram.com/oauth/authorize',token:'https://api.instagram.com/oauth/access_token',scope:'instagram_business_basic,instagram_business_content_publish',profile:'https://graph.instagram.com/me?fields=user_id,username,name,account_type,profile_picture_url'},
 TikTok:{clientId:'TIKTOK_CLIENT_KEY',secret:'TIKTOK_CLIENT_SECRET',authorize:'https://www.tiktok.com/v2/auth/authorize/',token:'https://open.tiktokapis.com/v2/oauth/token/',scope:'user.info.basic,video.publish,video.upload',profile:'https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url'},
 YouTube:{clientId:'YOUTUBE_CLIENT_ID',secret:'YOUTUBE_CLIENT_SECRET',authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scope:'https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly',profile:'https://www.googleapis.com/youtube/v3/channels?part=id,snippet&mine=true'}
};
function config(platform){const p=providers[platform];if(!p)throw Error('Plataforma não suportada.');return{...p,clientId:process.env[p.clientId],clientSecret:process.env[p.secret]}}
exports.status=()=>Object.keys(providers).map(platform=>{const p=config(platform);return{platform,configured:Boolean(p.clientId&&p.clientSecret),redirectUrl:`${base()}/${platform.toLowerCase()}/callback`}});
exports.authorization=(platform,userId)=>{const p=config(platform);if(!p.clientId||!p.clientSecret)throw Error(`Configure as credenciais oficiais do ${platform}.`);const state=jwt.sign({platform},process.env.JWT_SECRET,{subject:userId,expiresIn:'10m',algorithm:'HS256'}),redirectUri=`${base()}/${platform.toLowerCase()}/callback`,params=new URLSearchParams({client_id:p.clientId,redirect_uri:redirectUri,response_type:'code',scope:p.scope,state});if(platform==='TikTok')params.set('client_key',params.get('client_id')),params.delete('client_id');if(platform==='YouTube')params.set('access_type','offline'),params.set('prompt','consent');return`${p.authorize}?${params}`};
exports.exchange=async(platform,code,state)=>{const claim=jwt.verify(state,process.env.JWT_SECRET,{algorithms:['HS256']}),p=config(platform);if(claim.platform!==platform)throw Error('Estado OAuth inválido.');const redirectUri=`${base()}/${platform.toLowerCase()}/callback`,params=new URLSearchParams({code,grant_type:'authorization_code',redirect_uri:redirectUri});if(platform==='TikTok')params.set('client_key',p.clientId);else params.set('client_id',p.clientId);params.set('client_secret',p.clientSecret);const tokenResponse=await fetch(p.token,{method:'POST',headers:{'Content-Type':platform==='Instagram'?'application/x-www-form-urlencoded':'application/x-www-form-urlencoded'},body:params}),tokens=await tokenResponse.json();if(!tokenResponse.ok||tokens.error)throw Error(tokens.error_description||tokens.error?.message||tokens.error||'A plataforma recusou a autorização.');const accessToken=tokens.access_token,profileResponse=await fetch(p.profile,{headers:{Authorization:`Bearer ${accessToken}`}}),profile=await profileResponse.json();if(!profileResponse.ok)throw Error(profile.error?.message||'Não foi possível identificar a conta.');let id,name,avatar;if(platform==='YouTube'){const channel=profile.items?.[0];id=channel?.id;name=channel?.snippet?.title;avatar=channel?.snippet?.thumbnails?.default?.url}else if(platform==='TikTok'){id=profile.data?.user?.open_id;name=profile.data?.user?.display_name;avatar=profile.data?.user?.avatar_url}else{id=profile.user_id||profile.id;name=profile.username||profile.name;avatar=profile.profile_picture_url}if(!id)throw Error('A plataforma não retornou uma conta válida.');return{userId:claim.sub,platform,providerAccountId:String(id),accountName:String(name||id),profileUrl:avatar||null,encryptedCredentials:vault.encrypt(tokens),tokenExpiresAt:new Date(Date.now()+Number(tokens.expires_in||3600)*1000),scopes:tokens.scope||p.scope}}
;
