document.write('<script src="js/config.js"></script>');
document.write('<script src="js/navigation.js"></script>');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/navigation.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/dashboard-actions.css">');
const api=window.TORKS_API_URL||'http://localhost:3000/api',token=localStorage.getItem('torksToken');if(!token)location.href='login.html';
const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`},dialog=document.querySelector('#project-dialog'),projectsBody=document.querySelector('#projects-body');
const videosLink=document.querySelector('.dash nav a[href="#projects"]');if(videosLink)videosLink.href='videos.html';
const templatesLink=[...document.querySelectorAll('.dash nav a')].find(link=>link.textContent.trim()==='Templates');if(templatesLink)templatesLink.href='templates.html';
const schedulesLink=[...document.querySelectorAll('.dash nav a')].find(link=>['Agendamentos','Publicações'].includes(link.textContent.trim()));if(schedulesLink){schedulesLink.href='schedules.html';schedulesLink.textContent='Publicações'}
if(!document.querySelector('.dash nav a[href="conta.html"]'))document.querySelector('.dash nav').insertAdjacentHTML('beforeend','<a href="conta.html">Minha conta</a>');
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const statusLabel=value=>({ready:'Pronto',processing:'Processando',failed:'Falhou',draft:'Rascunho'}[value]||value);
const duration=seconds=>`${String(Math.floor((seconds||0)/60)).padStart(2,'0')}:${String((seconds||0)%60).padStart(2,'0')}`;
const date=value=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));
const projectRow=project=>`<tr><td><b>▶ ${escapeHtml(project.title)}</b></td><td><span class="status">${escapeHtml(statusLabel(project.status))}</span></td><td>${date(project.updatedAt)}</td><td>${duration(project.durationSeconds)}</td><td>${project.status!=='ready'?`<button class="delete-project" data-project-id="${project.id}" data-project-title="${escapeHtml(project.title)}">Excluir</button>`:'<span class="protected-project">Protegido</span>'}</td></tr>`;
async function apiFetch(path,options={}){const response=await fetch(`${api}${path}`,{...options,headers:{...headers,...options.headers}}),data=response.status===204?null:await response.json();if(response.status===401){localStorage.removeItem('torksToken');localStorage.removeItem('torksUser');location.href='login.html';throw Error(data?.error||'Sessão expirada.')}if(!response.ok)throw Error(data?.error||'Não foi possível concluir a operação.');return data}
function showUser(user){const firstName=user.name.trim().split(/\s+/)[0],initials=user.name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();document.querySelector('.user').innerHTML=`${escapeHtml(initials)} <span><b>${escapeHtml(user.name)}</b><small>${escapeHtml(user.email)}</small></span>`;document.querySelector('main header h1').innerHTML=`Olá, ${escapeHtml(firstName)} <em>✦</em>`;localStorage.setItem('torksUser',JSON.stringify(user))}
function showStats(projects){const totalSeconds=projects.reduce((sum,project)=>sum+Number(project.durationSeconds||0),0),ready=projects.filter(project=>project.status==='ready').length,completion=projects.length?Math.round(ready/projects.length*100):0,stats=document.querySelectorAll('.stats article b'),details=document.querySelectorAll('.stats article span');stats[0].textContent=projects.length;stats[1].textContent=`${Math.floor(totalSeconds/3600)}h ${Math.floor(totalSeconds%3600/60)}m`;stats[2].textContent='0';stats[3].textContent=`${completion}%`;details[0].textContent=`${projects.length} projetos cadastrados`;details[1].textContent=`${Math.ceil(totalSeconds/60)} minutos utilizados`;details[2].textContent='Disponível em uma próxima etapa';details[3].textContent=`${ready} projetos concluídos`;const planText=document.querySelector('.plan p');if(planText)planText.textContent=`${Math.ceil(totalSeconds/60)} de 60 minutos utilizados.`;const performance=document.querySelector('.chart-panel .big');if(performance)performance.innerHTML=`${projects.length} <em>projetos</em>`}
function showProjects(projects){projectsBody.innerHTML=projects.length?projects.map(projectRow).join(''):'<tr><td colspan="5">Você ainda não criou projetos.</td></tr>';document.querySelectorAll('.delete-project').forEach(button=>button.onclick=()=>openDeleteDialog(button.dataset.projectId,button.dataset.projectTitle))}
document.body.insertAdjacentHTML('beforeend',`<dialog id="delete-project-dialog"><form><h2>Excluir projeto?</h2><p id="delete-project-name"></p><p>Esta ação é permanente. Confirme com a senha da sua conta.</p><label>Senha atual<input id="delete-project-password" type="password" autocomplete="current-password" required></label><p class="delete-error" id="delete-project-error"></p><div class="dialog-actions"><button type="button" id="cancel-project-delete">Cancelar</button><button type="submit" class="danger-button">Excluir definitivamente</button></div></form></dialog>`);
const deleteDialog=document.querySelector('#delete-project-dialog');let pendingDeleteId=null;
function openDeleteDialog(id,title){pendingDeleteId=id;document.querySelector('#delete-project-name').textContent=title;document.querySelector('#delete-project-password').value='';document.querySelector('#delete-project-error').textContent='';deleteDialog.showModal()}
document.querySelector('#cancel-project-delete').onclick=()=>deleteDialog.close();
deleteDialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const password=document.querySelector('#delete-project-password').value,error=document.querySelector('#delete-project-error'),submit=event.submitter;if(!password)return;submit.disabled=true;try{await apiFetch(`/projects/${pendingDeleteId}/secure-delete`,{method:'POST',body:JSON.stringify({password})});deleteDialog.close();await loadDashboard()}catch(problem){error.textContent=problem.message}finally{submit.disabled=false}};
const projectsPanel=document.querySelector('#projects'),viewAllButton=projectsPanel?.querySelector('.panel-title button');if(viewAllButton)viewAllButton.onclick=()=>{location.href='videos.html'};const projectHeader=projectsPanel?.querySelector('thead tr');if(projectHeader&&projectHeader.children.length===4)projectHeader.insertAdjacentHTML('beforeend','<th>AÇÕES</th>');
async function loadDashboard(){try{const[userResult,projectsResult]=await Promise.all([apiFetch('/users/me'),apiFetch('/projects')]);showUser(userResult.data);showProjects(projectsResult.data);showStats(projectsResult.data)}catch(error){projectsBody.innerHTML=`<tr><td colspan="5">${escapeHtml(error.message||'Não foi possível carregar o dashboard.')}</td></tr>`}}
document.querySelector('#open-project').textContent='Criar com IA';document.querySelector('#open-project').onclick=()=>{location.href='criar.html'};
document.querySelectorAll('.quick button').forEach(button=>{button.onclick=()=>{if(button.dataset.type==='Template'){location.href='templates.html';return}location.href=`criar.html?modo=${encodeURIComponent(button.dataset.type)}`}});
document.querySelector('#save-project').onclick=async event=>{event.preventDefault();const titleInput=document.querySelector('#project-title'),title=titleInput.value.trim();if(!title)return titleInput.focus();try{await apiFetch('/projects',{method:'POST',body:JSON.stringify({title,type:document.querySelector('#project-type').value})});dialog.close();titleInput.value='';await loadDashboard()}catch(error){alert(error.message)}};
loadDashboard();
