document.write('<script src="js/config.js"></script>');
document.write('<script src="js/navigation.js"></script>');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/navigation.css">');
const api = window.TORKS_API_URL || 'http://localhost:3000/api';
const token = localStorage.getItem('torksToken');
if (!token) location.href = 'login.html';
const schedulesLink = Array.from(document.querySelectorAll('.dash nav a')).find(link => ['Agendamentos','Publicações'].includes(link.textContent.trim()));
if (schedulesLink) { schedulesLink.href = 'schedules.html'; schedulesLink.textContent = 'Publicações'; }
const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` };
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
let templates = [], selectedCategory = 'Todos', selectedTemplate;
async function apiFetch(path, options = {}) { const response = await fetch(`${api}${path}`, { ...options, headers: { ...headers, ...options.headers } }); const data = response.status === 204 ? null : await response.json(); if (response.status === 401) { localStorage.removeItem('torksToken'); location.href = 'login.html'; throw Error(data?.error); } if (!response.ok) throw Error(data?.error || 'Erro ao carregar templates.'); return data.data; }
function showUser(user) { const initials = user.name.trim().split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase(); document.querySelector('.user').innerHTML = `${escapeHtml(initials)} <span><b>${escapeHtml(user.name)}</b><small>${escapeHtml(user.email)}</small></span>`; }
function card(template) { const config = template.config || {}; return `<article class="template-card"><div class="template-preview" data-color="${escapeHtml(config.color || 'teal')}"><strong>✦</strong><span class="template-format">${escapeHtml(config.format || '9:16')}</span></div><div class="template-content"><span class="status">${escapeHtml(config.category || 'Geral')}</span><h2>${escapeHtml(template.name)}</h2><p>${escapeHtml(template.description || '')}</p><div class="template-meta"><span>${Number(config.duration || 15)} segundos</span><span>${escapeHtml(config.format || '9:16')}</span></div><button class="button use-template" data-id="${template.id}">Usar template</button></div></article>`; }
function render() { const search = document.querySelector('#template-search').value.trim().toLowerCase(); const filtered = templates.filter(item => (selectedCategory === 'Todos' || item.config?.category === selectedCategory) && (!search || `${item.name} ${item.description}`.toLowerCase().includes(search))); document.querySelector('#templates-grid').innerHTML = filtered.length ? filtered.map(card).join('') : '<div class="templates-empty">Nenhum template encontrado.</div>'; document.querySelectorAll('.use-template').forEach(button => button.onclick = () => openTemplate(button.dataset.id)); }
function openTemplate(id) { selectedTemplate = templates.find(item => item.id === id); document.querySelector('#selected-template-name').textContent = selectedTemplate.name; document.querySelector('#template-project-title').value = selectedTemplate.name; document.querySelector('#template-dialog').showModal(); }
async function load() { try { const [user, items] = await Promise.all([apiFetch('/users/me'), apiFetch('/templates')]); showUser(user); templates = items; const categories = [...new Set(items.map(item => item.config?.category).filter(Boolean))]; document.querySelector('#template-filters').innerHTML = ['Todos', ...categories].map(category => `<button class="${category === 'Todos' ? 'active' : ''}" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join(''); document.querySelectorAll('#template-filters button').forEach(button => button.onclick = () => { selectedCategory = button.dataset.category; document.querySelectorAll('#template-filters button').forEach(item => item.classList.toggle('active', item === button)); render(); }); render(); } catch (error) { document.querySelector('#templates-grid').innerHTML = `<div class="templates-empty">${escapeHtml(error.message)}</div>`; } }
document.querySelector('#template-search').oninput = render;
document.querySelector('#create-from-template').onclick = async event => { event.preventDefault(); const title = document.querySelector('#template-project-title').value.trim(); if (!title) return; try { await apiFetch('/projects', { method: 'POST', body: JSON.stringify({ title, type: `Template: ${selectedTemplate.name}` }) }); location.href = 'dashboard.html'; } catch (error) { alert(error.message); } };
load();
